introduction:
  title: Introduction to this task
  description: This task shows you how to handle an inbound call into your web app using the JavaScript Client SDK.
  content: |
    # Introduction
    In this tutorial, you will learn how to create a Client SDK application and then write the code to receive an
    inbound <abbr title="Public Switched Telephone Network">PSTN</abbr> call.
    To achieve this, you will need:
    * A web application that will notify the service agent of an inbound call and offer the ability to answer it
    * A webhook server that can process an inbound webhook and return an <abbr title="Nexmo Call Control Object">NCCO</abbr> to forward the inbound call to your application
prerequisites:
- create-nexmo-account
- install-nodejs
- install-node-client-sdk
- install-nexmo-cli-beta
- install-express
- run-ngrok

tasks:
- telephony/create-application
- buy-nexmo-number
- link-nexmo-number
- telephony/create-user
- telephony/generate-jwt
- telephony/phone-to-app/create-webhook-server
- telephony/phone-to-app/code
- telephony/phone-to-app/run

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |
    # What's next?
    You can do a lot more with the Client SDK.
    We want to hear what ideas you have in mind? Contact us at [devrel@nexmo.com](mailto:devrel@nexmo.com)
    See [Client SDK documentation](/client-sdk/overview).