navigation_weight:
  concepts: 1
  call-recording: 2
  provisioning: 3
  telephony: 4
  reports: 5
  vonage-integration-platform: 6
  smart-numbers: 7
  node-red: 8
  zapier: 9
  app-center: 10

navigation_overrides:
  concepts: 
    svg: 'mind-map'
  call-recording:
    svg: 'voicemail-2'
  provisioning:
    svg: 'address-book'
  node-red:
    svg: 'flow'
  reports:
    svg: 'report'
  smart-numbers:
    svg: 'brain'
  telephony:
    svg: 'telephone'
  vonage-integration-platform:
    svg: 'plug'
  zapier:
    svg: 'link'
  app-center:
    svg: 'rocket'
