---
"/call-recording/code-snippets": "/call-recording/overview#code-snippets"
"/call-recording/guides": "/call-recording/overview#guides"
"/provisioning/code-snippets": "/provisioning/overview#code-snippets"
"/provisioning/guides": "/provisioning/overview#guides"
"/telephony/code-snippets": "/telephony/overview#code-snippets"
"/telephony/guides": "/telephony/overview#guides"
"/reports/code-snippets": "/reports/overview#code-snippets"
"/reports/guides": "/reports/overview#guides"
"/vonage-integration-platform/code-snippets": "/vonage-integration-platform/overview#code-snippets"
"/vonage-integration-platform/guides": "/vonage-integration-platform/overview#guides"
"/smart-numbers/code-snippets": "/smart-numbers/overview#code-snippets"
"/smart-numbers/guides": "/smart-numbers/overview#guides"
